documentation: 
- "**/*.md"

CI:
- "**/*.yml"
- ".github/workflows/**/*"

bug: 
- "bug/*"

duplicate: 
- "duplicate/*"

help wanted: 
- "help wanted/*"

improve error message: 
- "improve error message/*"

invalid: 
- "invalid/*"

question: 
- "question/*"

waiting for feedback: 
- "waiting for feedback/*"

waiting on author: 
- "waiting on author/*"

websockets: 
- "websockets/*"

wontfix: 
- "wontfix/*"
